spring:
  application:
    name: Car-Rental-API-DDD
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rentals
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
  logging:
    level:
      root: info